### ISSUE TITLE
Debugging android-cmake Qt examples with Hunter libraries

### ISSUE THREAD

**Issue by pretyman** [forexample/android-cmake#1]
Hi @headupinclouds (and Ruslan!)

Do you have any advice on how to debug these Qt based examples?

I'm trying to debug these examples on QtCreator so I can start a Qt-based app, but I find no way to do with CMake + QtCreator. 

The route that I'm taking is to integrate Qt's QMake with Hunter and would like to know what are your thoughts in this subject.

Thanks!

**Comment by ruslo** [comment]
> Do you have any advice on how to debug these Qt based examples?

Don't know. You can take a look at http://cgold.readthedocs.io/en/latest/platforms/android/windows.html#debugging-with-visual-studio but this feature seems to be quite experimental. Also it requires to set a lot of stuff manually, awkward and error-prone.

> I'm trying to debug these examples on QtCreator so I can start a Qt-based app, but I find no way to do with CMake + QtCreator

Can you build this examples with QtCreator? As far as I understand you can run CMake build from inside of QtCreator, the only argument you need to pass is CMAKE_TOOLCHAIN_FILE.

> The route that I'm taking is to integrate Qt's QMake with Hunter and would like to know what are your thoughts in this subject.

Have no idea how to do it :) Also strategically Hunter is moving to opposite direction, wrap Qt tools (well, any tools) with CMake. We have Qt build scheme that wraps qmake with CMake and [qt-android-cmake](https://github.com/hunter-packages/qt-android-cmake/blob/hunter/AddQtAndroidApk.cmake) package that wraps androiddeployqt.

**Comment by headupinclouds** [comment]
Hi @pretyman.  Unfortunately, I may not have anything much to add to this.  I've been interesting in native C++ debugging (through IDE) on Android for a while.  I have had some success using remote gdb sessions in this past, but this was some time ago.  I believe I used a process very similar to this:

https://github.com/mapbox/mapbox-gl-native/wiki/Android-debugging-with-remote-GDB

**Comment by pretyman** [comment]
Thanks for your replies. 

There is also a very interesting article here: https://fw4spl-org.github.io/fw4spl-blog/2015/07/27/Native-debugging-on-Android-with-QtCreator.html but I don't think the gdbserver method is enough for QML debugging.

> Also strategically Hunter is moving to opposite direction, wrap Qt tools (well, any tools) with CMake. We have Qt build scheme that wraps qmake with CMake and qt-android-cmake package that wraps androiddeployqt.

Yeah, I understand that. When I get more acquainted with QML debugging, maybe I can come up with a solution to deal with it.

I'll evaluate the options, make some tests then come back to share the experience.

What I'm trying now is to:
1. dynamically create a toolchain.cmake file with the QMake configuration
2. dynamically create CMake scripts for each dependency to make hunter build the packages
3. add Hunter's `<root-it>/Install/include` to the `INCLUDEPATH` of QMake's target
4. somehow (?) extract the linking flags of the CMake target to add them to the QMake target

The challenge has been on number 4, to extract the linking flags from the packages to add them to QMake since they cannot be resolved at CMake configure time as they have generator expressions.

From a personal point of view, its sad that I'm dealing with QMake, since I started learning CMake to avoid QMake. However I feel that this would be the easiest for now, as I have to start developing and testing my app, and can't be fighting with the build system forever.

Feel free to comment. Hunter has been truly great to build Apps, but I feel that debugging is a crucial part of development, would be great if we could come up with a solution for it. 

I understand it's not Hunter's responsibility to deal with the debugging, but the end result for final user is that he loses debugging capabilities by using Hunter when it comes to developing with Qt or [when stepping into the package's source](https://github.com/ruslo/hunter/issues/359). I can definitely hack my way around it, but it is a show stopper for others.

**Comment by ruslo** [comment]
How do you originally build your app? It looks like you're starting QtCreator and set `*.pro` file as an entry point. You can use regular `cmake -H. -B_builds -DCMAKE_TOOLCHAIN_FILE=/path/to/android.cmake` command. Am I missing something?

> However I feel that this would be the easiest for now

This may be true for some simple cases, however in future you may hit more fundamental and big problems. From my experience fixing problems in place when they originally occurs is harder but works more smooth and yield more benefits in future. Again I may miss something but I think that original problem here is about CMake+QtCreator interconnection.

> when stepping into the package's source.

I agree that this part should be improved and will be useful but it's not a Hunter issue. If you build stuff manually and then upload it to server for reusage you can't do debugging too if your sources paths doesn't match build machine. Also it's not related to CMake, it's a general design issue.

**Comment by pretyman** [comment]
When trying the CMake script based project:

> How do you originally build your app? You can use regular cmake -H. -B_builds -DCMAKE_TOOLCHAIN_FILE=/path/to/android.cmake command. Am I missing something?
> In QtCreator, I setup a Custom Kit (Kit is a logic association of Compiler with Qt Version), with no Qt version, and CMake flags with -DCMAKE_TOOLCHAIN_FILE=/path/to/pollys/android.cmake

When I press the Debug button, it builds, and install the App on the device, but I get no target to debug and a Small dialog box appears asking me to start a custom executable, which I don't really know how to fill in :>

> I think that original problem here is about CMake+QtCreator interconnection.

Exactly, that's why I went the opposite way, from qmake integrate hunter.

> his may be true for some simple cases, however in future you may hit more fundamental and big problems. From my experience fixing problems in place when they originally occurs is harder but works more smooth and yield more benefits in future.

I completely agree, but it is just a LOT of knowledge I would have to gain to fix Creator (most important: a lot of time).

I ended up with something not too bad though, an API like:

``` QMake
INCLUDEPATH += $$hunter_install_include_path()

LIBS += $$hunter_package("hunter_package_name", "cmake_find_package call", "cmake_targets_to_link") 
```

I'm using for OpenCV, as per the example: https://github.com/ruslo/hunter/blob/master/examples/OpenCV/CMakeLists.txt#L12

``` QMake
LIBS += $$hunter_package("OpenCV", "OpenCV REQUIRED", "${OpenCV_LIBS}")
```

it's a semi-hack, but I'm starting to think this could be hammered into something that could be released in the wild and increase the chance to get hunter some more packages

I tried to update hunter's Qt for 5.7, but build stage did nothing for reasons that were hard to trace because I used the configure command line in a shell and it started compiling [but failed in the middle of compilation, which I did not investigate]. So I'm really going opposite direction here: using the official Qt SDK for Android, dynamically creating a toolchain file with qmake's settings and using it with hunter.

**Comment by ruslo** [comment]
> it is just a LOT of knowledge I would have to gain to fix Creator

You can ask about it in corresponding mailing list.

> most important: a lot of time

When I said "yield more benefits in future" I meant time too. Anyway I'm just sharing my experience, hope this experience will be useful for you: take a look at [Sugar](https://github.com/ruslo/sugar) project. I spent quite a lot of time for implementing hacks for supporting usiversal iOS build, it's like 3 versions of approaches and modules. Those modules **never** work well. Then I send patch upstream https://github.com/Kitware/CMake/commit/565d080a9a1e133bda868e905226181b60e90356 and now it works smooth, fast and stable, also available for a lot of peoples. Same will happen for [warning suppression](https://cmake.org/pipermail/cmake-developers/2016-April/028279.html) so everything that will left in Sugar will be two small `sugar_include` and `sugar_files` modules.

> but failed in the middle of compilation, which I did not investigate

Well, somebody will have to do it anyway.

As a summary even if you built something good and useful at a time when QtCreator-CMake chain will be improved and Qt 5.7 build in Hunter will be fixed, your approach will make no sense and will look awkward. Everything you did and all the time you spent will be lost.

**Comment by headupinclouds** [comment]
@pretyman:  I'd be interested to hear more about any progress you make towards full QT + QML debugging.  If you have the time, please share any findings here.  (I think I misread this post initially, btw).  I've been leaning on Xcode projects (via CMake + Hunter) on iOS and OS X to debug the C++ modules in my projects.  In my case, nearly all of the code is C++ and the QML sections are still quite minimal, so I have been able to get by so far.   (Android code is usually close enough to iOS to let me sort through any remaining issues with `adb logcat`).  I will need to leverage QML more in the future, however, so having a debugger to navigate those changes would be very useful.

**Comment by pretyman** [comment]
@headupinclouds : Using on-device testing only, I can tell you that QML debugging works, but QML enums are read as integers (I guess that's Qt's reponsibility's scope) and C++ works normally.

I guess that https://github.com/ruslo/hunter/issues/501 will help to use the QtSDK's Qt version with hunter packages dependent on Qt (odb-qt is what I'm planning on testing) by setting

``` CMake
hunter_config(Qt VERSION SYSTEM)
```

Hopefully this will also enable to use  https://github.com/hunter-packages/QtCMakeExtra with it?

**Comment by ruslo** [comment]
> Hopefully this will also enable to use

Nope, will not work.

**Comment by ruslo** [comment]
Closing inactive discussion.
