### ISSUE TITLE
HDF5

### ISSUE THREAD

**Issue by palmerc** [forexample/android-cmake#2]
Is it possible to build HDF5 using this setup? I'm attempting it but it is currently failing

**Comment by palmerc** [comment]
This test seems to fail:

CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   TEST_LFS_WORKS_RUN (advanced)
   TEST_LFS_WORKS_RUN__TRYRUN_OUTPUT (advanced)

I get the impression that Hunter must have patched these tests out since HDF5 attempts to configure itself via test programs running on the target, but this one isn't?

**Comment by palmerc** [comment]
OH... I don't think it works at all. I just set( HDF_ENABLE_LARGE_FILE off ) which gets passed that error and it moves on to all the live tests that typically make life difficult.

**Comment by palmerc** [comment]
So, it seems to fix this to be automagic you would need to check for this being a cross-compile Android build and then compile->transfer to device/emulator->run test program->read off results for each test for each desired architecture. I've seen something similar in a library called DCMTK.

**Comment by ruslo** [comment]
> Is it possible to build HDF5 using this setup?

This project is just a collection of examples. It's not directly related neither to Hunter nor HDF5. The best place to discuss fixes is https://github.com/hunter-packages/hdf5 .

Related: https://github.com/ruslo/hunter/issues/663
